### ISSUE TITLE
get-poetry is being deprecated in the 1.2.0 release

### ISSUE THREAD

**Issue by ITProKyle** [Gr1N/setup-poetry#16]
`get-poetry.py` is incapable of installing 1.2.0a1.

https://github.com/Gr1N/setup-poetry/blob/1163effedbd374337b2012c79b6204be2e2cd977/src/find.ts#L9

will need to be updated to the following:

```ts
  "https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py"
```

**Comment by nicolas-chaulet** [comment]
Should be fixed by #17

**Comment by Gr1N** [comment]
Hi everyone, thanks for the reminder. The installation script will be updated right after Poetry 1.2 will be released.

**Comment by ITProKyle** [comment]
@Gr1N - It would be beneficial to have the option to use the new script (or have it auto detect which script to use) prior to release to install the pre-release versions of 1.2.

There are features being implemented in 1.2 that can be tested and developed for (e.g. the new plugin system) ahead of the official release.

**Comment by Gr1N** [comment]
@ITProKyle I love that idea, will try to implement it in a few days

**Comment by Gr1N** [comment]
Released in `v5`. Also, please check the changelog there are some breaking changes https://github.com/Gr1N/setup-poetry#v5
