### ISSUE TITLE
Poetry no longer working with MacOS

### ISSUE THREAD

**Issue by kiancross** [Gr1N/setup-poetry#21]
This action used to work with MacOS, but it is now returning this error:

```
/Users/runner/work/_temp/151b84e0-098a-45b2-8502-13eb9d96059e.sh: line 1: poetry: command not found
```

**Comment by ITProKyle** [comment]
I am running into the same issue with the v6 release ([example](https://github.com/onicagroup/runway/pull/765/checks?check_run_id=3048791841#step:10:9))

**Comment by Gr1N** [comment]
@kiancross @ITProKyle thank you for the report.

Issue fixed in https://github.com/Gr1N/setup-poetry/releases/tag/v7. Hope this won't be broken in the future again because I've added tests for the macOS platform.
