### ISSUE TITLE
Upgrade action to node16

### ISSUE THREAD

**Issue by cpnielsen** [Gr1N/setup-poetry#31]
## Issue

Github is deprecating node12 actions, see blog post: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Upgrading the action to use `node16` and fixing any related discrepancies should silence this. The timeline is "summer 2023" so it's not _urgent_, but would be nice to get rid of the deprecation warnings.

**Comment by Gr1N** [comment]
Done, please try v8

https://github.com/Gr1N/setup-poetry/releases/tag/v8
