### ISSUE TITLE
poetry: command not found in python 3.11 on macos

### ISSUE THREAD

**Issue by wangxiaoying** [Gr1N/setup-poetry#33]
Below is the workflow (please find the full `yml` file [here](https://github.com/sfu-db/connector-x/blob/main/.github/workflows/release.yml)):

```
      - uses: Gr1N/setup-poetry@v7
      - run: poetry --version
```

And it shows error: `poetry: command not found`. [here](https://github.com/sfu-db/connector-x/actions/runs/3589790093/jobs/6042560464) is a failed running example.

Looks like the error only happens on macos with python 3.11.

Is there anything that I missed? Please let me know if you need more information.

**Comment by Gr1N** [comment]
Hey!

Can't reproduce. Can you please try with fresh v8?

https://github.com/Gr1N/setup-poetry/releases/tag/v8

**Comment by wangxiaoying** [comment]
Hi @Gr1N , switching to v8 works. Thank you!
