### ISSUE TITLE
Deprecated Versions?

### ISSUE THREAD

**Issue by jamesholland-uk** [Gr1N/setup-poetry#36]
Has v4 has been deprecated and removed? This is the error message observed yesterday:
```
Run Gr1N/setup-poetry@v4
  with:
    poetry-version: 1.0.10
    poetry-preview: false
  env:
    pythonLocation: <redacted>
Error: Unexpected HTTP response: 404
```
I noted that only v5 is documented in the readme, so I am right to infer that v4 has gone?
Thanks :-)

**Comment by Gr1N** [comment]
Hey, all versions are available to use. I guess you are stuck with the legacy URL for poetry installation. I recommend you to upgrade to the latest v8 version of the action.
