### ISSUE TITLE
The `add-path` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by brechtm** [Gr1N/setup-poetry#7]
When running my GitHub workflows, I'm seeing these warnings recently:
```
The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

I suspect these come from setup-poetry. The `dist/index.js` contains "add-path".

Thanks for this useful action!

**Comment by Gr1N** [comment]
Hi!

Thanks for the report. I will look into this ASAP.

**Comment by brechtm** [comment]
I think all that is needed is to upgrade _actions/core_ to 1.2.6, as in your _dependabot/npm_and_yarn/actions/core-1.2.6_ branch.

**Comment by Gr1N** [comment]
Yep, you are right. Just released v4 (`Gr1N/setup-poetry@v4`), enjoy!
